[libraries]
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1"
junit-junit = "junit:junit:4.13.2"
jackson-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.18.3"

